### ISSUE TITLE
启动压缩后内存占用过大

### ISSUE THREAD

**Issue by Bobyang912** [pruas/Biscuit#11]
从相册选择几张相片进行压缩，压缩前后，内存使用从4-50M一下子飙升到150多M,导致部分照片报“no enough memory”错误导致压缩失败，内存小的手机会直接崩溃

**Comment by pruas** [comment]
几张照片一下子加载到内存并压缩肯定会导致内存的大量使用的。 发生崩溃了吗？能否贴出崩溃日志？

**Comment by Bobyang912** [comment]
崩溃的情况是我猜测那些内存比较小的或者老款机型，手里的机器没出现，可能是你已经做了优化，这个不好意思，没出现的情况说出来有误导嫌疑了。只是出现因为内存原因导致压缩失败的，这种情况有办法解决么

**Comment by Bobyang912** [comment]
还有，我就算只选取一张图片做压缩，内存还是飙升的厉害，就是跑的你的这个demo

**Comment by pruas** [comment]
崩溃应该是不会发生的。最多是没有足够内存导致压缩失败。内存问题，特别大的图片加载到内存是没法避免压缩失败的。你可以在压缩监听里面 回收一下内存。 因为内存回收靠系统。在压缩成功的监听回调中调用以下代码回收内存：
```java
 Runtime.getRuntime().gc();
                try {
                    Thread.sleep(100);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
                System.runFinalization();
```
