### ISSUE TITLE
压缩一张图片以后，生成了20多个缓存文件

### ISSUE THREAD

**Issue by lk6233160** [pruas/Biscuit#12]
缓存文件并没有自动删除，得自己手动删，但是图片保存的位置也是缓存所在位置，会一起删掉
这块缓存处理是不是有点问题？

**Comment by pruas** [comment]
缓存是需要你代码删掉，请看文档。  没有自动删除一说。

**Comment by pruas** [comment]
另外压缩一张怎么生成20张缓存的？ 是压缩了二十次吧？

**Comment by lk6233160** [comment]
1、我知道你有预留方法啊，但是图片和缓存默认是在一个文件夹里，如果用.targetDir()这个方法 缓存和压缩好的图片仍然在一起....
2、压缩一张图片 生成了20个缓存文件 不是压缩了二十次

**Comment by pruas** [comment]
现在清除缓存方法是直接删除缓存目录下的文件，所以建议缓存文件位置单独，不要和其他文件混在一起。  另外压缩一张怎么有20张缓存？  这无论从代码还是逻辑都是不可能的。

**Comment by lk6233160** [comment]
缓存文件和压缩图片目前用的是一个位置， 只能把你代码copy到项目中改了
至于20个缓存我也很懵逼，我又测试了很多次，不是必现，到目前为止还没发现原因，只能先删除处理，手机是小米2S 系统是5.0.2。

**Comment by pruas** [comment]
缓存目录你是可以配置的啊  不用copy代码呀  引用库之后  在构建那 可以自定义缓存的路径。
