### ISSUE TITLE
 Out of memory on a 207667212-byte allocation.

### ISSUE THREAD

**Issue by Sabirjan** [pruas/Biscuit#14]
Oppo 手机  高清拍照  ，压缩失败。
`E/ImageCompressor: original size : 12147 KB
12-26 17:22:14.757 6632-6645/com.feihong.tupian D/dalvikvm: JIT code cache reset in 0 ms (0 bytes 1/0)
12-26 17:22:14.757 6632-6645/com.feihong.tupian D/dalvikvm: GC_FOR_ALLOC freed 300K, 11% free 3049K/3416K, paused 5ms, total 5ms
12-26 17:22:14.757 6632-6645/com.feihong.tupian D/dalvikvm: GC_FOR_ALLOC freed 8K, 11% free 3056K/3416K, paused 2ms, total 2ms
12-26 17:22:14.757 6632-6645/com.feihong.tupian I/dalvikvm-heap: Forcing collection of SoftReferences for 207667212-byte allocation
12-26 17:22:14.767 6632-6645/com.feihong.tupian D/dalvikvm: GC_BEFORE_OOM freed 2K, 11% free 3054K/3416K, paused 6ms, total 6ms
12-26 17:22:14.767 6632-6645/com.feihong.tupian E/dalvikvm-heap: Out of memory on a 207667212-byte allocation.
12-26 17:22:14.767 6632-6645/com.feihong.tupian I/dalvikvm: "HandlerExecutor" prio=10 tid=10 RUNNABLE
12-26 17:22:14.767 6632-6645/com.feihong.tupian I/dalvikvm:   | group="main" sCount=0 dsCount=0 obj=0x94f808f0 self=0xb8c4ed40
12-26 17:22:14.767 6632-6645/com.feihong.tupian I/dalvikvm:   | sysTid=6645 nice=0 sched=0/0 cgrp=[fopen-error:2] handle=-1194938432
12-26 17:22:14.777 6632-6645/com.feihong.tupian I/dalvikvm:   | state=R schedstat=( 0 0 0 ) utm=0 stm=1 core=0
12-26 17:22:14.777 6632-6645/com.feihong.tupian I/dalvikvm:     at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
12-26 17:22:14.777 6632-6645/com.feihong.tupian I/dalvikvm:     at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:613)
12-26 17:22:14.777 6632-6645/com.feihong.tupian I/dalvikvm:     at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:589)
12-26 17:22:14.777 6632-6645/com.feihong.tupian I/dalvikvm:     at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:369)
12-26 17:22:14.777 6632-6645/com.feihong.tupian I/dalvikvm:     at com.seek.biscuit.ImageCompressor.compress(ImageCompressor.java:73)
12-26 17:22:14.777 6632-6645/com.feihong.tupian I/dalvikvm:     at com.seek.biscuit.ImageCompressor.run(ImageCompressor.java:186)
12-26 17:22:14.777 6632-6645/com.feihong.tupian I/dalvikvm:     at com.seek.biscuit.HandlerExecutor$CompressHandler.handleMessage(HandlerExecutor.java:39)
12-26 17:22:14.777 6632-6645/com.feihong.tupian I/dalvikvm:     at android.os.Handler.dispatchMessage(Handler.java:102)
12-26 17:22:14.777 6632-6645/com.feihong.tupian I/dalvikvm:     at android.os.Looper.loop(Looper.java:136)
12-26 17:22:14.777 6632-6645/com.feihong.tupian I/dalvikvm:     at android.os.HandlerThread.run(HandlerThread.java:61)
12-26 17:22:14.777 6632-6645/com.feihong.tupian D/skia: --- decoder->decode returned false
12-26 17:22:14.777 6632-6645/com.feihong.tupian E/ImageCompressor: no enough memory!
12-26 17:22:14.787 6632-6632/com.feihong.tupian D/图压缩: onError() called with: e = [com.seek.biscuit.CompressException: no enough memory!]`

我的解决办法是;
`options.inPreferredConfig = Bitmap.Config.RGB_565;
        options.inDither = true;`

**Comment by Sabirjan** [comment]
BitmapFactory.decodeFile(sourcePath.path, options); 
这一行报内存溢出。

**Comment by pruas** [comment]
好的，感谢反馈。

**Comment by Sabirjan** [comment]
网上其他的解决办法是:
BitmapFactory.decodeFileDescriptor

**Comment by pruas** [comment]
你设置ignoreAlpha应该能解决你的问题

**Comment by Sabirjan** [comment]
嗯，可以解决。但是不知道这种解决办法是否正确。

**Comment by Sabirjan** [comment]
好的。我再研究研究，谢谢分享！
