### ISSUE TITLE
有内存泄漏问题，不知道哪个地方？

### ISSUE THREAD

**Issue by Sabirjan** [pruas/Biscuit#15]
有内存泄漏问题。压缩5个图片， 不关闭窗口，每次批量压缩，内存差不多 15-20Mb增。
图片大小 20MB , 10MB  ,3MB  1MB 
写了System.gc 没有很大的作用。

**Comment by Sabirjan** [comment]
App 开着状态，等了10分钟，没有被回收。

**Comment by pruas** [comment]
并没有啊。你压缩完 内存就下降了。但是有个压缩线程还开着，页面关掉就跟着销毁了。你可能对内存泄露改变并不是很深入了解。

**Comment by Sabirjan** [comment]
一样的图片，一样的页面。Luban 11MB ， 这个程序 26MB 内存
也许吧。我再研究研究或者选Luban吧
