### ISSUE TITLE
can`nt save exif info! 这是什么错误

### ISSUE THREAD

**Issue by for7GG** [pruas/Biscuit#16]
can`nt save exif info!

**Comment by Gru110110110** [comment]
就是保存EXIF信息出现问题了。

**Comment by for7GG** [comment]
能不能保存exif信息出错也继续保存图片，小米5 Android8.0，每次拍照后压缩图片就报这个错误

**Comment by Gru110110110** [comment]
这个错已经catch掉了，只不过我打印一下log而已。你可以看看[这个方法的处理](https://github.com/pruas/Biscuit/blob/master/library/src/main/java/com/seek/biscuit/ImageCompressor.java#L193)，不影响保存的啊。
