### ISSUE TITLE
能否提供压缩图片的算法步骤？

### ISSUE THREAD

**Issue by HortonGou** [pruas/Biscuit#4]
请问Biscuit与Luban在性能上有过比较吗？毕竟功能上比较相似。
再有就是能否像Luban一样提供压缩算法步骤，这样方便在ios上也实现相同的图片压缩方式

**Comment by pruas** [comment]
算法在代码里了。你直接看代码就ok。  具体步骤我找个时间描述一下。 性能上比Luban要健壮很多，主要是做了很多严谨的检查，另外看代码实现也能看出很大区别的，有时候说不如看代码来的爽快。实现方式上最接近微信（精确缩放），Luban只是inSample压缩，众所周知，inSample的值只是2的冥数级，而Biscuit是默认精准缩放的，所以Biscuit压缩出来的大小、宽高和微信比较一致。这个在我贴出来的图就能看出来了。不过该库，仅仅在我的手机上测试，所以不知道其他手机会有所差异，需要更多数据才能调整更完善的算法。

**Comment by HortonGou** [comment]
不知道Biscuit是否处理了图片多次压缩的问题。一张5M的图片微信压缩到615k之后，这张615k的图再上传就不再压缩了，而Luban会再次压缩到100k左右吧。不知道这种情况Biscuit会不会再次压缩直到ignoreLessThan的大小

**Comment by HortonGou** [comment]
另外据说ExifInterface这类在低版本有安全漏洞，能否考虑使用v4包中的？
大概多次压缩这个目前猜测微信可能限制了size<width x height /(1024 x 16)的图片不压缩，只是初步猜测还未验证

**Comment by pruas** [comment]
Biscuit现在并不去获取ExifInterface信息。  ignoreLessThan这个是设置忽略传入的原图小于这个值的不压缩。 多次压缩目前还没做限制。但是不会像你说的615k再次压缩到100多k。再次压缩少于原来几k吧，实验数据看来。

**Comment by HortonGou** [comment]
Utils中获取旋转角度的时候的确是调用了ExifInterface的

**Comment by pruas** [comment]
只是提供这个方法。。。但是没有使用在压缩上。

**Comment by HortonGou** [comment]
似乎Biscuit只提供了异步回调的方法，然后还提供了一个自定义的executor的方法。能否提供一个同步的阻塞方法？可以方便在RxJava2中的io线程中使用

**Comment by pruas** [comment]
executor就是需要你在子线程执行的  否则就是同步阻塞。你可以自定义executor使用rxjava来执行传进来的Runnable对象就达到你的目的。另外推导过程分析已经加在README里。
