### ISSUE TITLE
批量压缩是否有个全部压缩完成的 listener

### ISSUE THREAD

**Issue by L5411** [pruas/Biscuit#6]
Listener只是监听单张图片压缩完成，批量压缩时就会多次调用 listener，是否有批量压缩的listener

**Comment by L5411** [comment]
多图压缩出现 Background partial concurrent mark sweep GC freed 77970(11MB) AllocSpace objects, 0(0B) LOS objects, 31% free, 35MB/51MB, paused 3.607ms total 100.509ms

**Comment by pruas** [comment]
目前没有加入批量压缩完成的提示方法，不过也很好解决，在监听回调中收到事件就统计一下（不管是成功还少失败）,当统计数等于传入的批量数，就标志完成了。 压缩出现那个不影响吧？

**Comment by L5411** [comment]
好的，我试试
