### ISSUE TITLE
算法很好，希望加入压缩到指定大小的功能

### ISSUE THREAD

**Issue by fuchaothb** [pruas/Biscuit#7]
算法很好，希望加入压缩到指定大小的功能

**Comment by pruas** [comment]
指定大小不是很好控制，因为各人需求可能不一，比如你传入（400，400），而要压缩的图片是（1080，1920），是以宽为准压缩至（400，711）呢，还是以高为准压缩至（225，400），还是不按比例宁愿丢掉部分直接暴力生成（400，400）？
