### ISSUE TITLE
希望可以添加这个压缩,JNI调用libjpeg库压缩

### ISSUE THREAD

**Issue by 900326** [pruas/Biscuit#8]
希望可以添加这个压缩,JNI调用libjpeg库压缩,了解了下这个压缩后的大小和清晰度都更好,但是压缩速度慢,尤其发布类似朋友圈的多图功能,选择多图后压缩要很长时间,技术有限,希望借助楼主的能力实现下

**Comment by mrme2014** [comment]
https://github.com/mrme2014/imgcompress-master

利用libjpeg.so  来实现的压缩
