### ISSUE TITLE
使用文件原名称有问题

### ISSUE THREAD

**Issue by CrazySongCN** [pruas/Biscuit#9]
public ImagePath(String path) {
        this.path = path;
        int typeSplit = path.lastIndexOf(".");
        int nameSplit = path.lastIndexOf("/");
        if (typeSplit != -1 && nameSplit != -1) {
            this.name = path.substring(nameSplit + 1, typeSplit - 1);
        }
        if (typeSplit != -1) {
            this.type = path.substring(typeSplit, path.length());
        }
    }
中            this.name = path.substring(nameSplit + 1, typeSplit - 1); 会导致文件名的最后一个字母被删掉。。。能尽快修复吗？现在通过library用

**Comment by pruas** [comment]
不好意思，没注意，已经修改。另外提供同步方法可以使用。详细见使用例子。
